### PR TITLE
Added IridiumSkyblock & UltimateClaims support

### PR DESCRIPTION
**Pull request by Khontrom**
Added IridiumSkyblock & UltimateClaims support

### CODE REVIEW

**Comment by Khontrom** [comment]
Added İridiumSkyblock support

**Comment by Khontrom** [comment]
Added UltimateClaims Support

**Review by poyrazinan — CHANGES_REQUESTED** [review]
- Needed documentation on IridiumListener
- Needed documentation on UltimateListener

All the other things seems ok, thank you for adding 2 more plugin hook to Farmer!
Waiting your update :)

**Review by poyrazinan — APPROVED** [review]
Thank you

**Pull request merged**
