### PR TITLE
Update

### PR DESCRIPTION
**Pull request by Justman100**

### CODE REVIEW

**Comment by Keithsguest** [comment]
funny how were both here looking at this right now and its not even listed on their website anymore

**Comment by Keithsguest** [comment]
> _ No description provided. _

here were are

**Comment by Justman100** [comment]
> funny how were both here looking at this right now and its not even listed on their website anymore

???

**Comment by Justman100** [comment]
@poyrazinan

**Comment by Justman100** [comment]
@poyrazinan

**Review by poyrazinan — APPROVED** [review]

**Comment by Justman100** [comment]
@poyrazinan

Why the fuck are you removing my changes to the language files WITHOUT CLEARING THAT? The wording and especially the translations are complete shit because they are incorrect!!!

**Comment by Justman100** [comment]
> @poyrazinan
> 
> Why the fuck are you removing my changes to the language files WITHOUT CLEARING THAT? The wording and especially the translations are complete shit because they are incorrect!!!

Wait... Why is the directory structure different in develope?

**Comment by Justman100** [comment]
In addition, my PR was based on the main branche, so it should actually be merged there as well

**Comment by poyrazinan** [comment]
They will be removed in a short while and also i will be change the language files according to your corrections. But they are not exists in develop with yml format.

**Pull request merged**
